defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - node_modules
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - new_post
  - package.json
  - package-lock.json
  - README.md

plugins:
  - jekyll-sitemap

disqus_shortname: edrums
