defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude: ["Gemfile", "Gemfile.lock", "new_post", "CNAME"]

plugins_dir:
  - jekyll-sitemap

disqus_shortname: edrums
