name: Deploy site

on: { push: { branches: [master] } }

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          # needed for accurate dates and blog plugin
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install Poetry
        run: python3 -m pip install --upgrade poetry
      - name: Cache build data
        uses: actions/cache@v3
        with:
          key: mkdocs-cache-${{ runner.os }}-${{ hashFiles('**/poetry.lock', '**/mkdocs.yml') }}
          path: .cache
      - name: Install dependencies
        run: poetry install
      - name: Download assets
        run: poetry run python3 scripts/download.py
      - name: Build assets
        run: poetry run python3 scripts/uglify-assets.py
      - name: Build and deploy
        run: poetry run mkdocs gh-deploy --force
